tst_model: tst_mo.o model.o events.o 
	cc68x -g tst_mo.o model.o events.o -o model_ts

tst_mo.o: tst_mo.c model.h
	cc68x -g -c tst_mo.c
	
model.o: model.c model.h
	cc68x -g -c model.c

events.o: events.c events.h
	cc68x -g -c events.c

