#ifndef BITMAPS_H
#include "TYPES.H"

#define ASIAN_FACING_RIGHT 32
#define TRASHCAN 32
#define CHOPSTICKS 16

extern const UINT16 chopsticks_moving_left[CHOPSTICKS];
extern const UINT16 chopsticks_moving_right[CHOPSTICKS];
extern const UINT32 asian_facing_left_bitmap[ASIAN_FACING_RIGHT];
extern const UINT32 asian_facing_right_bitmap[ASIAN_FACING_RIGHT];
extern const UINT32 trashcan_bitmap[TRASHCAN];

#endif